//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Deu2000.rc
//
#define IDR_MANIFEST                    100
#define IDD_ABOUTBOX                    101
#define IDP_OLE_INIT_FAILED             102
#define IDR_DATAPANE                    103
#define IDD_DLG_PROPERTY                104
#define IDR_DATA                        105
#define IDC_LIST_VIEW                   106
#define IDR_PANE1                       107
#define IDR_PANE2                       108
#define ID_VECTORPANEL_SDE              108
#define ID_VECTORPANEL                  109
#define IDC_TAB1                        110
#define IDC_TAB_FROMAT                  110
#define IDR_VECTOR_SDE                  110
#define IDR_RASTERDOC                   111
#define IDD_DLG_TASK                    112
#define IDS_STRING112                   112
#define IDR_TASKPANE                    113
#define ID_RASTERPANEL                  114
#define IDR_MAINFRAME                   115
#define IDR_TABMANTYPE                  116
#define IDB_TABCTRL_ICONS               117
#define IDR_VECTORDOC                   118
#define IDD_DIALOG_PROPERTIES           119
#define IDB_BITMAP1                     120
#define IDB_BITMAP2                     121
#define IDR_PROPERTYPANE                122
#define IDR_DEU2000MENU                 123
#define IDR_STACKPANE                   124
#define IDR_OVERVIEW                    125
#define IDR_MESSAGEPANE                 126
#define IDB_BITMAP3                     127
#define IDB_BITMAP4                     128
#define IDB_BITMAP5                     129
#define IDC_TREETASK                    130
#define ID_VIEW_SWITCH_THEME            131
#define IDR_TOOLBAR1                    132
#define IDB_LARGEICON                   133
#define IDR_TOOLBAR2                    134
#define IDR_TOOLBAR3                    135
#define IDI_ICON_VIEW                   136
#define IDB_TREEIMG                     137
#define ID_VECTOR                       138
#define ID_ZOOM_IN                      139
#define ID_RASTER                       140
#define ID_ZOOM_OUT                     141
#define IDB_CHINAMAP                    142
#define ID_VIEW                         143
#define IDD_DLG_VECTOR                  144
#define ID_PREV                         145
#define IDD_DLG_PANEL_TAB               146
#define ID_LAST                         147
#define IDD_DLG_SOURCE                  148
#define ID_SELECT                       149
#define ID_SELECTCANCEL                 150
#define IDD_DLG_CONTROL_POINT           151
#define ID_REMOVELAYOUT                 152
#define ID_SOURCE                       153
#define IDR_MENUCONTEXT                 154
#define ID_HANDMOVE                     155
#define ID_DEFAULTSTATE                 156
#define ID_GLOBAL                       157
#define ID_TMP                          158
#define ID_HORIZATOL                    159
#define ID_OVERVIEW                     160
#define IDD_DLG_LOGIN                   161
#define IDD_DLG_VIEW                    162
#define IDC_BTN_UPDATE_CP               163
#define IDC_BTN_USERS_UPDATE            164
#define IDC_BTN_UGROUP_SAVE             165
#define IDC_BTN_CREATE_CP               166
#define IDC_EDIT3                       167
#define IDC_BTN_USER_CLOSE              168
#define IDC_BTN_IMPORT_CP               169
#define IDC_BTN_EXPORT_CP               170
#define IDC_MAPPIC                      171
#define IDR_MENU_LIST_PT                172
#define IDC_BTN_REMOVE                  173
#define IDC_BTN_OUTPUT                  174
#define IDB_SAVE                        175
#define IDB_DEL                         176
#define IDC_BTN_TASK_PROCESS            177
#define IDC_BTN_TASK_PROCESSALL         178
#define IDC_BTN_TASK_REMOVE             179
#define IDC_BTN_TASK_REMOVEALL          180
#define IDD_DLG_BACKGROUND              181
#define IDC_BTN_TASK_ADD                182
#define IDD_DLG_USERS_OPERA             183
#define IDC_BTN_TASK_BATADD             184
#define IDD_DLG_USERGROUPS_OPERA        185
#define IDC_COMBO_INPUT                 186
#define IDI_ICON_UGROUP                 187
#define IDC_PROGRESS1                   188
#define IDD_DLG_CP                      189
#define IDC_STATIC_INPUTFIELD           190
#define IDD_DLG_SOURCE_DETAIL           191
#define IDC_STATIC_OUTPUTFIELD          192
#define IDC_BTN_INPUT                   193
#define IDC_COMBO_OUTPUT                194
#define IDD_DLG_FILE                    195
#define IDC_STATIC_INPUT_TYPE           196
#define IDD_DLG_ORACLE                  197
#define IDC_STATIC_OUTPUT_TYPE          198
#define IDD_DLG_ORA_TABLES              199
#define IDC_COMBO_TRANMODEL             200
#define IDD_DLG_PROJECTED               201
#define IDC_BTN_EXE                     202
#define IDD_DLG_GEODETIC                203
#define IDC_COMBO_RECOLLECT             204
#define IDC_STATIC_INPUT_LABEL          205
#define IDD_DLG_RASTERSETTING           206
#define IDC_STATIC_OUTPUTLABEL          207
#define IDC_EDIT_INPUT                  208
#define IDC_EDIT_OUTPUT                 209
#define IDR_Deu2000TYPE                 210
#define IDC_COMBO_TRANSFER              211
#define IDC_COMBO_SRC                   212
#define IDC_COMBO_DEST                  213
#define IDC_BTN_UPDATE_UGROUP           214
#define IDC_STATIC_POS                  215
#define IDC_MAPVIEW                     216
#define IDC_TREE1                       217
#define IDC_STATIC_MODEL                218
#define IDC_STATIC_PT                   219
#define IDC_STATIC_SRC                  220
#define IDC_STATIC_DEST                 221
#define IDC_STATIC_SRC_X                222
#define IDC_STATIC_SRC_Y                223
#define IDC_STATIC_SRC_Z                224
#define IDC_STATIC_DEST_X               225
#define IDC_STATIC_DEST_Y               226
#define IDC_STATIC_DEST_Z               227
#define IDC_EDIT_SRC_X                  228
#define IDC_EDIT_SRC_Y                  229
#define IDC_EDIT_SRC_Z                  230
#define IDC_EDIT_DEST_X                 231
#define IDC_EDIT_DEST_Y                 232
#define IDC_EDIT_DEST_Z                 233
#define IDC_LIST_CONTROL_PT             234
#define IDC_TAB                         235
#define IDD_DLG_USERS                   236
#define IDD_DLG_USERGROUPS              237
#define IDR_HTML_DEUDLGBACKGROUND       238
#define IDD_DLG_SOURCE_CUSTOM           239
#define IDC_BTN_USERS_SAVE              240
#define IDD_DLG_SOURCE_CUSTOM_DETAIL    241
#define IDC_LIST_UROLE_SRC              242
#define IDC_PROPERTY_GRID               243
#define IDC_LIST2                       244
#define IDC_LIST_RASTER                 244
#define IDC_LIST_ELLIP                  244
#define ID_ITEM_VERSION_LANGUAGE        245
#define IDC_EDIT1                       246
#define IDC_PROID                       246
#define IDC_EDIT_IN_D                   246
#define IDC_EDIT_PATH                   246
#define IDC_EDIT_CPNUM                  246
#define IDC_ED_SERVER                   246
#define IDC_ED_X_SRC                    246
#define IDC_EDIT_USERNAME               247
#define IDC_EDIT17                      247
#define IDC_PWD                         247
#define IDC_EDIT_IN_L                   247
#define IDC_ED_SERVICE                  247
#define IDC_EDIT_DES                    247
#define IDC_ED_Y_SRC                    247
#define IDC_EDIT_False_Easting          247
#define IDC_EDIT_UGROUPNAME             248
#define IDC_EDIT_IN_H                   248
#define IDC_ED_DATABASE                 248
#define IDC_ED_Z_SRC                    248
#define IDC_EDIT_False_Northing         248
#define IDC_EDIT_OUT_D                  249
#define IDC_ED_USERNAME                 249
#define IDC_ED_XO_SRC                   249
#define IDC_EDIT_Central_Meridian       249
#define IDS_GROUP_CHECKED_TRUE          250
#define IDC_EDIT_OUT_L                  250
#define IDC_ED_PASSWORD                 250
#define IDC_ED_YO_SRC                   250
#define IDC_EDIT_ORA_SID                251
#define IDC_EDIT_OUT_H                  251
#define IDC_ED_VERSION                  251
#define IDC_ED_ZO_SRC                   251
#define IDC_BUTTON3                     252
#define IDC_EDIT_IN_H3                  252
#define IDC_EDIT_OUT_BT                 252
#define IDC_BTN_GRID                    252
#define IDC_ED_K_SRC                    252
#define IDC_BUTTON_Geographic           252
#define IDC_EDIT_COORINATE_OUTPUT       253
#define IDC_ED_X_DES                    253
#define IDC_BUTTON_PROJECTED            253
#define IDC_EDIT_MINLONG                254
#define IDC_ED_Y_DES                    254
#define IDS_GROUP_CHECKED_FALSE         255
#define IDC_ED_Z_DES                    255
#define IDC_EDIT_ORA_USERS              256
#define IDC_ED_XO_DES                   256
#define IDC_EDIT4                       257
#define IDC_ED_YO_DES                   257
#define IDC_BUTTON7                     258
#define IDC_ED_ZO_DES                   258
#define IDC_BTN_UROLE_SELECTALL         259
#define IDC_ED_K_DES                    259
#define IDC_EDIT_MAXLONG                260
#define IDS_GROUP_ATTACHMENTS_TRUE      261
#define IDC_EDIT_ORA_PWD                262
#define IDC_EDIT6                       263
#define IDC_BTN_UROLE_REMOVE            264
#define IDC_EDIT_MAXLONG2               265
#define IDS_GROUP_ATTACHMENTS_FALSE     266
#define IDC_EDIT7                       267
#define IDC_BTN_UROLE_REMOVEALL         268
#define IDC_EDIT_MINLONG2               269
#define IDC_EDIT8                       270
#define IDC_EDIT_USERPWD                271
#define IDC_EDIT9                       272
#define IDB_IMPORT                      273
#define IDC_EDIT10                      274
#define IDC_EDIT_CM                     275
#define IDC_LIST1                       276
#define IDC_EDIT11                      277
#define IDC_EDIT_FE                     278
#define IDC_LIST_UROLE_DEST             279
#define IDC_EDIT12                      280
#define IIDC_EDIT_ELLIPSOID_PIANXIN     281
#define IDC_EDIT_SRC                    282
#define IDC_EDIT13                      283
#define IDC_EDIT_ELLIPSOID_SHORT        284
#define IDC_EDIT_DEST                   285
#define ID_EXPORT                       286
#define ID_RASTERPROJECT                287
#define IDR_PROJECTDOC                  288
#define IDR_VECTORPROJECTDOC            289
#define IDC_COMBO_PRONAME               290
#define ID_PROJECT                      291
#define IDC_COMBO_FX                    292
#define IDC_STATIC_RECOLLECT            293
#define IDD_DLG_GRIDSETTING             294
#define IDC_EDIT_COORINATE_INPUT        295
#define IDC_STATIC_PROC                 296
#define IDC_BTN_CREATE_UGROUP           297
#define IDC_BTN_DEL_UGROUP              298
#define IDC_BTN_USERS_CREATE            299
#define IDC_BTN_USERS_CANCEL            300
#define IDC_BTN_USERS_DEL               301
#define IDC_BTN_LOGIN_CANCEL            302
#define IDC_BTN_LOGIN_ENTER             303
#define IDC_EDIT_ACCOUNT                304
#define IDC_BTN_UROLE_SELECT            305
#define IDC_CHK_SGE                     306
#define IDC_CHK_SLE                     307
#define IDC_CHK_DBE                     308
#define IDC_CHK_SGC                     309
#define IDC_CHK_SLC                     310
#define IDC_CHK_DBC                     311
#define IDC_BTN_UGROUP_CANCEL           312
#define IDC_DBE                         313
#define IDC_SLE                         314
#define IDC_SGE                         315
#define IDC_DBC                         316
#define IDC_SLC                         317
#define IDC_SGC                         318
#define IDC_LABEL_COODINATE_INPUT       319
#define IDC_LABEL_COODINATE_INPUT2      320
#define IDC_BTNCP_OK                    321
#define IDC_BTNCP_CANCEL                322
#define IDC_EDIT2                       323
#define IDC_EDIT5                       324
#define IDC_EDIT_MINLAT                 325
#define IDC_EDIT_MAXLAT                 326
#define IDC_EDIT14                      327
#define IDC_EDIT_MAXLAT2                328
#define IDC_EDIT15                      329
#define IDC_BTN_DETAIL_1                330
#define IDC_EDIT16                      331
#define IDC_BTN_DETAIL_2                332
#define IDC_BTN_DETAIL_3                333
#define IDC_EDIT_NAME                   334
#define IDC_EDIT_REMARK                 335
#define IDC_BTN_CLOSE                   336
#define IDC_PLACEHOLDER                 337
#define IDC_STATIC_DESCRIPT             338
#define IDC_                            339
#define IDC_BTN_EXPLORER                340
#define IDC_STATIC_PATH                 341
#define IDC_COMBO_PATH                  341
#define IDC_LIST_FILES                  342
#define IDC_CHECK1                      343
#define IDC_BTN_OK                      344
#define IDC_BTN_CONNTEST                345
#define IDC_BTN_CANCEL                  346
#define IDC_COMBO1                      347
#define IDC_COMBO_GP                    348
#define IDC_COMBO_Coordinate_Name       348
#define IDC_EDIT_ENVELOPE_NAME          349
#define IDC_EDIT_ENVELOPE_MIN_LONG      350
#define IDC_EDIT_ENVELOPE_MIN_FLAT      351
#define IDC_EDIT_ENVELOPE_MAX_LONG      352
#define IDC_EDIT_ENVELOPE_MAX_FLAT      353
#define IDC_EDIT_ELLIPSOID_NAME         354
#define IDC_EDIT_ELLIPSOID_LONG         355
#define IDC_CHECK2                      356
#define IDC_CHK_DEM                     357
#define IDC_BTN_ANNOT                   358
#define IDC_BTN_ANNOTATION              359
#define IDC_BUTTON1                     360
#define IDC_BTN_INSTALL                 360
#define IDC_BUTTON_BR                   360
#define IDC_BTN_SETLIST                 360
#define IDC_BTN_FILE                    360
#define IDC_BTN_CONNECT                 360
#define IDC_BTN_SRC                     360
#define IDC_BTN_SETTING                 361
#define IDC_RADIO1                      362
#define IDC_RADIONONSTD                 363
#define IDC_RADIO_resample              364
#define IDC_RADIO2                      365
#define IDC_RADIOSTD                    366
#define IDC_RADIO_transfer              367
#define ID_VECTORPROJECT                368
#define IDC_BTN_GRIDSETTING             369
#define IDC_BTN_PORT_CP                 370
#define ID_32771                        371
#define ID_VIEW_PROPERTIES              372
#define ID_32772                        373
#define ID_32773                        374
#define ID_32774                        375
#define ID_32775                        376
#define ID_32776                        377
#define ID_32777                        378
#define ID_32778                        379
#define ID_32779                        380
#define ID_32780                        381
#define ID_32781                        382
#define ID_32782                        383
#define ID_32783                        384
#define ID_32784                        385
#define ID_32785                        386
#define ID_32786                        387
#define ID_32787                        388
#define ID_32788                        389
#define ID_32789                        390
#define ID_32790                        391
#define ID_32791                        392
#define ID_32792                        393
#define ID_32793                        394
#define ID_32794                        395
#define ID_32795                        396
#define ID_32796                        397
#define ID_32797                        398
#define ID_32798                        399
#define ID_32799                        400
#define ID_32800                        401
#define ID_32801                        402
#define ID_32802                        403
#define ID_HSC                          404
#define ID_APP                          405
#define ID_CREATE                       406
#define ID_32828                        407
#define ID_32829                        408
#define ID_TRAN_DEF                     409
#define ID_LINEAR_UNIT                  410
#define ID_ELLIPOSID                    411
#define ID_ANGULAR_UNIT                 412
#define ID_ABOUT                        413
#define ID_32836                        414
#define ID_32837                        415
#define ID_32838                        416
#define ID_32839                        417
#define ID_32840                        418
#define ID_IMPORT                       419
#define ID_DELROW                       420
#define ID_DEL_ALL                      421
#define ID_USERS                        422
#define ID_USERGROUP                    423
#define ID_32848                        424
#define ID_CREATE_CP                    425
#define ID_32850                        426
#define ID_DATA_DETAIL                  427
#define ID_32852                        428
#define ID_32853                        429
#define ID_PROJECTED_ADD                430
#define ID_GEODEITC_ADD                 431
#define ID_OVERLAP                      432
#define ID_MODIFYGEODEITC               433
#define ID_32858                        434
#define ID_MODIFYPROJECTED              435
#define ID_32860                        436
#define ID_                             437
#define ID_GRIDSETTING                  438
#define ID_GRIDSET                      439
#define IDD_DLG_FL                      10189
#define IDD_DLG_FL_GRID                 10189
#define IDD_DLG_EXCEL                   10190
#define IDD_DLG_SGFL_GRID               10191
#define IDD_DLG_CPLIST                  10194
#define IDD_DLG_FROMATSET               10195
#define IDR_TOOLBAR4                    10198
#define IDD_DLG_ELLIP_MANAGER           10204
#define IDD_DLG_CONNECTION              10205
#define IDD_DLG_VECTOR_SDE              10206
#define IDD_DIALOG1                     10207
#define IDD_DLG_SHOW                    10207
#define IDD_DLG_SETPARAMS               10208
#define IDD_DLG_ADD_GEODETIC            10209
#define IDD_DLG_ADD_PROJECTED           10210
#define IDC_COMBO_ACCOUNT               11132
#define IDC_STATIC88                    11133
#define IDC_COMBO_INPUT_RULE            11134
#define IDC_STATIC_INPUT_RULE           11135
#define IDC_STATIC_OUT_RULE             11136
#define IDC_COMBO_OUT_RULE              11137
#define IDC_BUTTON2                     11138
#define IDC_BUTTON_BRC                  11138
#define IDC_OutPutPara                  11138
#define IDC_OUT_PUT_PARA                11138
#define IDC_BTN_DES                     11138
#define IDC_EDIT_PATHC                  11139
#define ID_OK                           11140
#define IDC_CUSTOM1                     11141
#define IDC_GRID                        11141
#define IDC_LIST_VECTOR                 11142
#define IDC_CHECK_SAME                  11143
#define IDC_TREE_ELLIP                  11143
#define IDC_COMBO_MOUDEL                11144
#define IDC_STATIC_COR                  11145
#define IDC_STATIC_DS                   11146
#define IDC_STATIC_DES                  11147
#define IDC_STATIC_MOUDEL               11148
#define IDC_LIST_SHOW                   11151
#define IDC_BTN_INPUTPARAM              11152
#define IDC_STC_INVP                    11153
#define IDC_STC_IN                      11154
#define IDC_STC_X_DES                   11155
#define IDC_STC_Y_DES                   11156
#define IDC_STC_Z_DES                   11157
#define IDC_STC_XO_DES                  11158
#define IDC_STC_YO_DES                  11159
#define IDC_STC_ZO_DES                  11160
#define IDC_STC_K_DES                   11161
#define IDC_COMBO_ELLIPSOID_NAME        11162
#define IDC_COMBO_unit                  11164
#define IDC_EDIT_unit_data              11165
#define IDC_EDIT_ELLIPSOID_a            11166
#define IDC_EDIT_ELLIPSOID_k            11167
#define IDC_EDIT_ELLIPSOID_b            11168
#define IDC_COMBO_Project_Type          11169
#define ID_32864                        32864
#define ID_32865                        32865
#define ID_32866                        32866
#define ID_32867                        32867
#define ID_32868                        32868
#define ID_32869                        32869
#define ID_32870                        32870
#define ID_32871                        32871
#define ID_32872                        32872
#define ID_Map_Inform                   32873
#define ID_FL_                          32874
#define ID_FL_ADD                       32875
#define ID_FL_DELETE                    32876
#define ID_Menu                         32877
#define ID_FORMAT                       32878
#define ID_Menu32881                    32881
#define ID_VECTOR_SDE                   32882

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10212
#define _APS_NEXT_COMMAND_VALUE         32882
#define _APS_NEXT_CONTROL_VALUE         11171
#define _APS_NEXT_SYMED_VALUE           10225
#endif
#endif
